<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ENV_UPDATE_PROCESSOR [
	<!ELEMENT ENV_UPDATE_PROCESSOR (LAUNCH_APP_ON_EXIT)>
	<!ELEMENT LAUNCH_APP_ON_EXIT (ENABLE, PATH, ARGUMENTS, ACCOUNT_NAME, ACCOUNT_PWD, VISIBLE)>
	<!ELEMENT ARGUMENTS (ARGUMENT*)>  
	<!ELEMENT ENABLE (#PCDATA)>  
	<!ELEMENT PATH (#PCDATA)>  
	<!ELEMENT ARGUMENT (#PCDATA)>  
	<!ELEMENT ACCOUNT_NAME (#PCDATA)>  
	<!ELEMENT ACCOUNT_PWD (#PCDATA)>
	<!ELEMENT VISIBLE (#PCDATA)>	
]>
<ENV_UPDATE_PROCESSOR>
	<LAUNCH_APP_ON_EXIT>
		<ENABLE>1</ENABLE>
		<PATH></PATH>
		<ARGUMENTS>
			<ARGUMENT>@D:\moodmedia\software_v5\settings\startup.ini</ARGUMENT>
		</ARGUMENTS>
		<ACCOUNT_NAME>stream01</ACCOUNT_NAME>
		<ACCOUNT_PWD>retr9xEt</ACCOUNT_PWD>
		<VISIBLE>1</VISIBLE>
	</LAUNCH_APP_ON_EXIT>
</ENV_UPDATE_PROCESSOR>
