<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ENVIRONMENTS[
  <!ELEMENT ENVIRONMENTS (HARDWARE, SOFTWARE, CLIENT)>
  <!ELEMENT HARDWARE (ENV_VERSION)>
  <!ELEMENT SOFTWARE (ENV_VERSION)>
  <!ELEMENT CLIENT (ENV_VERSION)>
  <!ELEMENT ENV_VERSION (#PCDATA)>
]>
<ENVIRONMENTS>
  <HARDWARE>
    <ENV_VERSION>16</ENV_VERSION>
  </HARDWARE>
  <SOFTWARE>
    <ENV_VERSION>55</ENV_VERSION>
  </SOFTWARE>
  <CLIENT>
    <ENV_VERSION>19</ENV_VERSION>
  </CLIENT>
</ENVIRONMENTS>