<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE HARDWARE_SETTINGS[
  <!ELEMENT HARDWARE_SETTINGS (ENVIRONMENT, SERIAL_NUMBER, WINDOWS_ACCOUNTS)>
  <!ELEMENT ENVIRONMENT (ENV_NAME, EARLY_ADOPTER)>
  <!ELEMENT WINDOWS_ACCOUNTS (ACCOUNT+)>
  <!ELEMENT ACCOUNT (ACCOUNT_ID, NAME, PWD)>
  <!ELEMENT ENV_NAME (#PCDATA)>
  <!ELEMENT EARLY_ADOPTER (#PCDATA)>
  <!ELEMENT SERIAL_NUMBER (#PCDATA)>
  <!ELEMENT ACCOUNT_ID (#PCDATA)>
  <!ELEMENT NAME (#PCDATA)>
  <!ELEMENT PWD (#PCDATA)>
]>
<HARDWARE_SETTINGS>
  <ENVIRONMENT>
    <ENV_NAME>MVP425_WES7</ENV_NAME>
    <EARLY_ADOPTER>0</EARLY_ADOPTER>
  </ENVIRONMENT>
  <SERIAL_NUMBER>PC100001</SERIAL_NUMBER>
  <WINDOWS_ACCOUNTS>
    <ACCOUNT>
      <ACCOUNT_ID>1</ACCOUNT_ID>
      <NAME>stream01</NAME>
      <PWD>retr9xEt</PWD>
    </ACCOUNT>
  </WINDOWS_ACCOUNTS>
</HARDWARE_SETTINGS>