<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE NETWORK_SETTINGS [
     <!ELEMENT NETWORK_SETTINGS (PROXY, WIRED_NETWORK, WIRELESS_NETWORK)>
     <!ELEMENT PROXY (ENABLED,ADDRESS,PORT,USER,PWD)>
     <!ELEMENT ENABLED (#PCDATA)>
     <!ELEMENT ADDRESS (#PCDATA)>
     <!ELEMENT PORT (#PCDATA)>
     <!ELEMENT USER (#PCDATA)>
     <!ELEMENT PWD (#PCDATA)>
     <!ELEMENT WIRED_NETWORK (NETWORK_CONNECTION)>
     <!ELEMENT WIRELESS_NETWORK (NETWORK_CONNECTION, SSID, SECURITY_KEY, SECURITY_KEY_TYPE )>
     <!ELEMENT NETWORK_CONNECTION (NETWORK_ENABLED, DHCP_ENABLED, IP_ADDRESS, IP_MASK, IP_GATEWAY,AUTOMATIC_DNS,DNS_IP_1,DNS_IP_2)>
     <!ELEMENT NETWORK_ENABLED (#PCDATA)>
     <!ELEMENT DHCP_ENABLED (#PCDATA)>
     <!ELEMENT IP_ADDRESS (#PCDATA)>
     <!ELEMENT IP_MASK (#PCDATA)>
     <!ELEMENT IP_GATEWAY (#PCDATA)>
     <!ELEMENT AUTOMATIC_DNS (#PCDATA)>
     <!ELEMENT DNS_IP_1 (#PCDATA)>
     <!ELEMENT DNS_IP_2 (#PCDATA)>
     <!ELEMENT SSID (#PCDATA)>
     <!ELEMENT SECURITY_KEY (#PCDATA)>
     <!ELEMENT SECURITY_KEY_TYPE (#PCDATA)>
]>
<NETWORK_SETTINGS>
  <PROXY>
    <ENABLED>0</ENABLED>
    <ADDRESS></ADDRESS>
    <PORT>0</PORT>
    <USER></USER>
    <PWD></PWD>
  </PROXY>
  <WIRED_NETWORK>
    <NETWORK_CONNECTION>
      <NETWORK_ENABLED>1</NETWORK_ENABLED>
      <DHCP_ENABLED>1</DHCP_ENABLED>
      <IP_ADDRESS></IP_ADDRESS>
      <IP_MASK></IP_MASK>
      <IP_GATEWAY></IP_GATEWAY>
      <AUTOMATIC_DNS>1</AUTOMATIC_DNS>
      <DNS_IP_1></DNS_IP_1>
      <DNS_IP_2></DNS_IP_2>
    </NETWORK_CONNECTION>
  </WIRED_NETWORK>
  <WIRELESS_NETWORK>
    <NETWORK_CONNECTION>
      <NETWORK_ENABLED>0</NETWORK_ENABLED>
      <DHCP_ENABLED>0</DHCP_ENABLED>
      <IP_ADDRESS />
      <IP_MASK />
      <IP_GATEWAY />
      <AUTOMATIC_DNS>0</AUTOMATIC_DNS>
      <DNS_IP_1 />
      <DNS_IP_2 />
    </NETWORK_CONNECTION>
    <SSID></SSID>
    <SECURITY_KEY></SECURITY_KEY>
    <SECURITY_KEY_TYPE></SECURITY_KEY_TYPE>
  </WIRELESS_NETWORK>
</NETWORK_SETTINGS>