<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE RECOVERY_SETTINGS [
  <!ELEMENT RECOVERY_SETTINGS (RECOVERY_MODE, DISABLE_SCREENS_ON_RECOVERY, MEMORY_LIMIT_PERCENTAGE, PRIVATE_MEMORY_LIMIT, HANDLE_LIMIT, TRIGGER_ON_MEMORY, TRIGGER_ON_HANDLE, TRIGGER_ON_VIDEO_PLAYBACK_ERROR, TRIGGER_ALL)>  
  <!ELEMENT RECOVERY_MODE (#PCDATA)>
  <!ELEMENT DISABLE_SCREENS_ON_RECOVERY (#PCDATA)>
  <!ELEMENT MEMORY_LIMIT_PERCENTAGE (#PCDATA)>
  <!ELEMENT PRIVATE_MEMORY_LIMIT (#PCDATA)>
  <!ELEMENT HANDLE_LIMIT (#PCDATA)>
  <!ELEMENT TRIGGER_ON_MEMORY (#PCDATA)>
  <!ELEMENT TRIGGER_ON_HANDLE (#PCDATA)>
  <!ELEMENT TRIGGER_ON_VIDEO_PLAYBACK_ERROR (#PCDATA)>
  <!ELEMENT TRIGGER_ALL (#PCDATA)>
]>
<RECOVERY_SETTINGS>
	<RECOVERY_MODE>RESTART</RECOVERY_MODE>
	<DISABLE_SCREENS_ON_RECOVERY>FALSE</DISABLE_SCREENS_ON_RECOVERY>
	<!--<RECOVERY_MODE>REBOOT</RECOVERY_MODE>-->
	<!--<RECOVERY_MODE>RESTART</RECOVERY_MODE>-->
	<!--<RECOVERY_MODE>NONE</RECOVERY_MODE>-->
	<MEMORY_LIMIT_PERCENTAGE>90</MEMORY_LIMIT_PERCENTAGE><!--90 fo top6 is fine but need at least 95 for BAT -->
	<PRIVATE_MEMORY_LIMIT>1200000</PRIVATE_MEMORY_LIMIT><!--Size in KB -->
	<HANDLE_LIMIT>15000</HANDLE_LIMIT>
	<TRIGGER_ON_MEMORY>ON</TRIGGER_ON_MEMORY>
	<TRIGGER_ON_HANDLE>OFF</TRIGGER_ON_HANDLE>
	<TRIGGER_ON_VIDEO_PLAYBACK_ERROR>ON</TRIGGER_ON_VIDEO_PLAYBACK_ERROR>
	<TRIGGER_ALL>ON</TRIGGER_ALL>
</RECOVERY_SETTINGS>