<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE SOFTWARE[
  <!ELEMENT SOFTWARE (ENVIRONMENT, TEAMCO, GDL, PURGE, WCF, TMPFOLDER, HASH_EXTENSION, RELOAD_SETTINGS_INTERVAL, DEBUG_MODE)>
  <!ELEMENT ENVIRONMENT (ENV_NAME, EARLY_ADOPTER)>
  <!ELEMENT TEAMCO (PLAYLIST, LOGDB, LOG_PLAYED_DB, MEDIA_FILES, LOOP_IN_ZONE)>
  <!ELEMENT PLAYLIST (TCPATH, TCPWD)>
  <!ELEMENT LOGDB (DBPATH , DBPWD, VERBOSE)>
  <!ELEMENT LOG_PLAYED_DB (DBPATH , DBPWD, MEDIA_MIN_DURATION_FOR_LOG)>
  <!ELEMENT GDL (GDL_WCF)>
  <!ELEMENT GDL_WCF (GDL_SERVER_IP, GDL_PORT, GDL_ENDPOINT)>
  <!ELEMENT PURGE (PURGE_MEDIA_FILES, PURGE_LOGS, PURGE_CUSTOM)>
  <!ELEMENT PURGE_MEDIA_FILES (WITH_PLAYLIST, UNTOUCHED_DAYS)>
  <!ELEMENT PURGE_LOGS (UNTOUCHED_DAYS)>
  <!ELEMENT PURGE_CUSTOM (PURGE_CUSTOM_TARGET*)>
  <!ELEMENT PURGE_CUSTOM_TARGET (PURGE_CUSTOM_DIR, INCLUDE_SUBDIR, PURGE_CUSTOM_PATTERN, UNTOUCHED_DAYS)>
  <!ELEMENT WCF (END_POINTS)>
  <!ELEMENT END_POINTS (EP_ROOT, EP_RUNAS, EP_KEY_LISTENER, EP_RUNASLAUNCHER)>
  <!ELEMENT RUNAS_SERVER (END_POINT)>
  <!ELEMENT ENV_NAME (#PCDATA)>
  <!ELEMENT EARLY_ADOPTER (#PCDATA)>
  <!ELEMENT VERBOSE (#PCDATA)>
  <!ELEMENT DBPATH (#PCDATA)>
  <!ELEMENT DBPWD (#PCDATA)>
  <!ELEMENT MEDIA_MIN_DURATION_FOR_LOG (#PCDATA)>
  <!ELEMENT MEDIA_FILES (#PCDATA)>
  <!ELEMENT LOOP_IN_ZONE   (#PCDATA)>
  <!ELEMENT TCPATH (#PCDATA)>
  <!ELEMENT TCPWD (#PCDATA)>
  <!ELEMENT GDL_SERVER_IP (#PCDATA)>
  <!ELEMENT GDL_PORT (#PCDATA)>
  <!ELEMENT GDL_ENDPOINT (#PCDATA)>
  <!ELEMENT WITH_PLAYLIST (#PCDATA)>
  <!ELEMENT UNTOUCHED_DAYS (#PCDATA)>
  <!ELEMENT PURGE_CUSTOM_DIR (#PCDATA)>
  <!ELEMENT INCLUDE_SUBDIR (#PCDATA)>
  <!ELEMENT PURGE_CUSTOM_PATTERN (#PCDATA)>
  <!ELEMENT END_POINT (#PCDATA)>  
  <!ELEMENT TMPFOLDER (#PCDATA)>
  <!ELEMENT END_POINT_ROOT (#PCDATA)>
  <!ELEMENT HASH_EXTENSION (#PCDATA)>
  <!ELEMENT RELOAD_SETTINGS_INTERVAL (#PCDATA)>
  <!ELEMENT EP_ROOT (#PCDATA)>
  <!ELEMENT EP_RUNAS (#PCDATA)>
  <!ELEMENT EP_KEY_LISTENER (#PCDATA)>
  <!ELEMENT EP_RUNASLAUNCHER (#PCDATA)>
  <!ELEMENT DEBUG_MODE (#PCDATA)>
]>
<SOFTWARE>
  <ENVIRONMENT>
    <ENV_NAME>TEAMCO_PLAYER</ENV_NAME>
    <EARLY_ADOPTER>1</EARLY_ADOPTER>
  </ENVIRONMENT>
  <TEAMCO>
    <PLAYLIST>
      <TCPATH>D:\moodmedia\playlist\playlist_v5.sdf</TCPATH>
      <TCPWD>tiep5lus</TCPWD>
    </PLAYLIST>
    <LOGDB>
      <DBPATH>D:\moodmedia\logs\logs_v5.sdf</DBPATH>
      <DBPWD>tiep5lus</DBPWD>
      <VERBOSE>False</VERBOSE>
    </LOGDB>
    <LOG_PLAYED_DB>
      <DBPATH>D:\moodmedia\logs\played.sdf</DBPATH>
      <DBPWD>tiep5lus</DBPWD>
      <MEDIA_MIN_DURATION_FOR_LOG>1000</MEDIA_MIN_DURATION_FOR_LOG>
    </LOG_PLAYED_DB>
    <MEDIA_FILES>d:\media_files</MEDIA_FILES>
    <LOOP_IN_ZONE>True</LOOP_IN_ZONE>
  </TEAMCO>
  <GDL>
    <GDL_WCF>
      <GDL_SERVER_IP>http://127.0.0.1</GDL_SERVER_IP>
      <GDL_PORT>81</GDL_PORT>
      <GDL_ENDPOINT>gdl</GDL_ENDPOINT>
    </GDL_WCF>
  </GDL>
  <PURGE>
    <PURGE_MEDIA_FILES>
      <WITH_PLAYLIST>0</WITH_PLAYLIST>
      <UNTOUCHED_DAYS>15</UNTOUCHED_DAYS>
    </PURGE_MEDIA_FILES>
    <PURGE_LOGS>
      <UNTOUCHED_DAYS>7</UNTOUCHED_DAYS>
    </PURGE_LOGS>
    <PURGE_CUSTOM>
      <PURGE_CUSTOM_TARGET>
        <PURGE_CUSTOM_DIR>d:\tmp\</PURGE_CUSTOM_DIR>
        <INCLUDE_SUBDIR>True</INCLUDE_SUBDIR>
        <PURGE_CUSTOM_PATTERN>*.*</PURGE_CUSTOM_PATTERN>
        <UNTOUCHED_DAYS>7</UNTOUCHED_DAYS>
      </PURGE_CUSTOM_TARGET>
    </PURGE_CUSTOM>
  </PURGE>
  <WCF>
    <END_POINTS>
      <EP_ROOT>wcf</EP_ROOT>
      <EP_RUNAS>runas</EP_RUNAS>
      <EP_KEY_LISTENER>klistener</EP_KEY_LISTENER>
      <EP_RUNASLAUNCHER>runaslauncher</EP_RUNASLAUNCHER>
    </END_POINTS>
  </WCF>
  <TMPFOLDER>d:\tmp\</TMPFOLDER>
  <HASH_EXTENSION>.sha</HASH_EXTENSION>
  <RELOAD_SETTINGS_INTERVAL>300000</RELOAD_SETTINGS_INTERVAL>
  <DEBUG_MODE>False</DEBUG_MODE>
</SOFTWARE>