<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TCV5_PLAYLISTER_SETTINGS[
  <!ELEMENT TCV5_PLAYLISTER_SETTINGS (VIDEO_ENGINE_PATH, RELOAD_PLAYLIST_PERIOD, ON_MISSING_MEDIA_FILE_PLAY_SCREENSAVER, ENABLE_PLAYBACK_MONITORING_LOGS, ADVANCED, SPECIFIC_STATISTICS)>  
  <!ELEMENT ADVANCED (SLEEP_TIME_BETWEEN_STREAM_LAUNCH, SLEEP_TIME_BEFORE_STREAM_LAUNCH_AND_PLAYLIST_PARSING)>
  <!ELEMENT SLEEP_TIME_BETWEEN_STREAM_LAUNCH (#PCDATA)>
  <!ELEMENT SLEEP_TIME_BEFORE_STREAM_LAUNCH_AND_PLAYLIST_PARSING (#PCDATA)>
  <!ELEMENT VIDEO_ENGINE_PATH (#PCDATA)>
  <!ELEMENT RELOAD_PLAYLIST_PERIOD (#PCDATA)>
  <!ELEMENT ON_MISSING_MEDIA_FILE_PLAY_SCREENSAVER (#PCDATA)>
  <!ELEMENT ENABLE_PLAYBACK_MONITORING_LOGS (#PCDATA)>
  <!ELEMENT SPECIFIC_STATISTICS (#PCDATA)>
]>
<TCV5_PLAYLISTER_SETTINGS>
  <VIDEO_ENGINE_PATH>D:\moodmedia\software_v5\TeamCoV5.Player.Winform.exe</VIDEO_ENGINE_PATH>
  <RELOAD_PLAYLIST_PERIOD>5000</RELOAD_PLAYLIST_PERIOD>
  <ON_MISSING_MEDIA_FILE_PLAY_SCREENSAVER>False</ON_MISSING_MEDIA_FILE_PLAY_SCREENSAVER>
  <ENABLE_PLAYBACK_MONITORING_LOGS>False</ENABLE_PLAYBACK_MONITORING_LOGS>
  <ADVANCED>
    <!-- TODO :  sleep_time_between_stream_launch not used in code for now-->
    <SLEEP_TIME_BETWEEN_STREAM_LAUNCH>200</SLEEP_TIME_BETWEEN_STREAM_LAUNCH>
    <SLEEP_TIME_BEFORE_STREAM_LAUNCH_AND_PLAYLIST_PARSING>2000</SLEEP_TIME_BEFORE_STREAM_LAUNCH_AND_PLAYLIST_PARSING>
  </ADVANCED>
  <SPECIFIC_STATISTICS>
  </SPECIFIC_STATISTICS>
</TCV5_PLAYLISTER_SETTINGS>