<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE VIDEO_ENGINE_SETTINGS [
  <!ELEMENT VIDEO_ENGINE_SETTINGS (SPLASHSCREEN_BUFFER_MESSAGE, SCREENSAVER_BUFFER_MESSAGE, COMMANDS, ADVANCED)>  
  <!ELEMENT COMMANDS (KILL_CURRENT_STREAM, KILL_ALL, TOGGLE_AUTO_BRING_TO_FRONT)>
  <!ELEMENT ADVANCED (IS_VIDEO_SYNC_ON_AUDIO_CLOCK, NO_BUFFER_SLEEP_TIME, RELOAD_BUFFER_SLEEP_TIME, PLAY_TIMER_OFFSET_PERCENTAGE, DXVA, DXVA_OPTIMISATION, DXVA_RESTRICTION, DXVA_PIPES_NUMBER, ENABLE_DSHOW_EVR, SOURCE_FILER_CLSID,DXVA_SOURCE_FILER_CLSID, SPLITER_CLSID, DXVA_SPLITER_CLSID, DEFAULT_DSHOW_DECODER_NAME, DEFAULT_DXVA_DECODER_NAME, DEFAULT_AUDIO_DECODER_CLSID, AUDIO_RENDERER_CONFIG?, VIDEO_CONTROLS_TIMEOUT, DEFAULT_STREAMS_BACKGROUND_COLOR, DEFAULT_ZONES_BACKGROUND_COLOR, DEFAULT_ZONES_BACKGROUND_IMAGE, CAPTURE_DEVICES, TUNER_DEVICES, TV_CHANNELS, AUTO_BRING_TO_FRONT,FLASHS_WELL_CODED, DISABLE_BUFFERING, MINIMIZE_BUFFERING)>
  <!ELEMENT DXVA_OPTIMISATION (ENABLE, DXVA_MIN_WIDTH, DXVA_MIN_HEIGHT, DXVA_MAX_WIDTH, DXVA_MAX_HEIGHT)>
  <!ELEMENT SPLASHSCREEN_BUFFER_MESSAGE (#PCDATA)>
  <!ELEMENT SCREENSAVER_BUFFER_MESSAGE (#PCDATA)>
  <!ELEMENT KILL_CURRENT_STREAM (#PCDATA)>
  <!ELEMENT KILL_ALL (#PCDATA)>
  <!ELEMENT IS_VIDEO_SYNC_ON_AUDIO_CLOCK (#PCDATA)>
  <!ELEMENT NO_BUFFER_SLEEP_TIME (#PCDATA)>
  <!ELEMENT RELOAD_BUFFER_SLEEP_TIME (#PCDATA)>
  <!ELEMENT PLAY_TIMER_OFFSET_PERCENTAGE (#PCDATA)>
  <!ELEMENT DXVA (#PCDATA)>
  <!ELEMENT ENABLE (#PCDATA)>
  <!ELEMENT DXVA_MIN_WIDTH (#PCDATA)>
  <!ELEMENT DXVA_MIN_HEIGHT (#PCDATA)>
  <!ELEMENT DXVA_MAX_WIDTH (#PCDATA)>
  <!ELEMENT DXVA_MAX_HEIGHT (#PCDATA)>
  <!ELEMENT DXVA_RESTRICTION (#PCDATA)>
  <!ELEMENT DXVA_PIPES_NUMBER (#PCDATA)>  
  <!ELEMENT ENABLE_DSHOW_EVR (#PCDATA)> 
  <!ELEMENT SOURCE_FILER_CLSID (#PCDATA)> 
  <!ELEMENT DXVA_SOURCE_FILER_CLSID (#PCDATA)> 
  <!ELEMENT SPLITER_CLSID (#PCDATA)> 
  <!ELEMENT DXVA_SPLITER_CLSID (#PCDATA)> 
  <!ELEMENT DEFAULT_DSHOW_DECODER_NAME (#PCDATA)> 
  <!ELEMENT DEFAULT_DXVA_DECODER_NAME (#PCDATA)> 
  <!ELEMENT DEFAULT_AUDIO_DECODER_CLSID (#PCDATA)> 
  <!ELEMENT AUDIO_RENDERER_CONFIG (STREAM*)> 
  <!ELEMENT STREAM (LEFT_PERCENT,TOP_PERCENT,WIDTH_PERCENT,HEIGHT_PERCENT,RENDERER_NAME)> 
  <!ELEMENT LEFT_PERCENT (#PCDATA)>
  <!ELEMENT TOP_PERCENT (#PCDATA)>
  <!ELEMENT WIDTH_PERCENT (#PCDATA)>
  <!ELEMENT HEIGHT_PERCENT (#PCDATA)>
  <!ELEMENT RENDERER_NAME (#PCDATA)>
  <!ELEMENT VIDEO_CONTROLS_TIMEOUT (#PCDATA)> 
  <!ELEMENT DEFAULT_STREAMS_BACKGROUND_COLOR (#PCDATA)>
  <!ELEMENT DEFAULT_ZONES_BACKGROUND_COLOR (#PCDATA)>
  <!ELEMENT DEFAULT_ZONES_BACKGROUND_IMAGE (#PCDATA)>
  <!ELEMENT CAPTURE_DEVICES (#PCDATA)>
  <!ELEMENT TUNER_DEVICES (#PCDATA)>
  <!ELEMENT TV_CHANNELS (#PCDATA)>
  <!ELEMENT AUTO_BRING_TO_FRONT (#PCDATA)>
  <!ELEMENT FLASHS_WELL_CODED (#PCDATA)>
  <!ELEMENT DISABLE_BUFFERING (#PCDATA)>
  <!ELEMENT MINIMIZE_BUFFERING (#PCDATA)>
  <!ELEMENT TOGGLE_AUTO_BRING_TO_FRONT (#PCDATA)>
]>
<VIDEO_ENGINE_SETTINGS>
  <SPLASHSCREEN_BUFFER_MESSAGE>D:\moodmedia\software_v5\settings\splash_screen.xml</SPLASHSCREEN_BUFFER_MESSAGE>
  <SCREENSAVER_BUFFER_MESSAGE>d:\moodmedia\project\screen_saver\screen_saver_v5.xml</SCREENSAVER_BUFFER_MESSAGE>
  <COMMANDS>
	<KILL_CURRENT_STREAM>a</KILL_CURRENT_STREAM>
	<KILL_ALL>b</KILL_ALL>
    <TOGGLE_AUTO_BRING_TO_FRONT>front</TOGGLE_AUTO_BRING_TO_FRONT>
  </COMMANDS>
  <ADVANCED>
	<IS_VIDEO_SYNC_ON_AUDIO_CLOCK>True</IS_VIDEO_SYNC_ON_AUDIO_CLOCK>
	<NO_BUFFER_SLEEP_TIME>100</NO_BUFFER_SLEEP_TIME>
	<RELOAD_BUFFER_SLEEP_TIME>100</RELOAD_BUFFER_SLEEP_TIME>
	<PLAY_TIMER_OFFSET_PERCENTAGE>10</PLAY_TIMER_OFFSET_PERCENTAGE>
	<DXVA>1</DXVA>
	<DXVA_OPTIMISATION>
		<ENABLE>0</ENABLE>
		<DXVA_MIN_WIDTH>1920</DXVA_MIN_WIDTH>
		<DXVA_MIN_HEIGHT>1080</DXVA_MIN_HEIGHT>
		<DXVA_MAX_WIDTH>1920</DXVA_MAX_WIDTH>
		<DXVA_MAX_HEIGHT>1080</DXVA_MAX_HEIGHT>
	</DXVA_OPTIMISATION>
	<DXVA_RESTRICTION>0</DXVA_RESTRICTION><!-- restric DXVA pipe pool to only 1 output per graphic card-->
	<DXVA_PIPES_NUMBER>1</DXVA_PIPES_NUMBER>
	<ENABLE_DSHOW_EVR>0</ENABLE_DSHOW_EVR><!-- 0= disable, 1 = enable -->
	<!--<SOURCE_FILER_CLSID>{E436EBB5-524F-11CE-9F53-0020AF0BA770}</SOURCE_FILER_CLSID>--><!--File Source (Async.)-->
	<!--<SOURCE_FILER_CLSID>{55DA30FC-F16B-49FC-BAA5-AE59FC65F82D}</SOURCE_FILER_CLSID>--><!--Haali Media Splitter-->
	<SOURCE_FILER_CLSID>{B98D13E7-55DB-4385-A33D-09FD1BA26338}</SOURCE_FILER_CLSID><!--LAV Splitter Source-->
	<DXVA_SOURCE_FILER_CLSID>{B98D13E7-55DB-4385-A33D-09FD1BA26338}</DXVA_SOURCE_FILER_CLSID><!--LAV Splitter Source-->
	<!--<SPLITER_CLSID>{55DA30FC-F16B-49FC-BAA5-AE59FC65F82D}</SPLITER_CLSID>--><!--Haali Media Splitter(AR)-->
	<!--<SPLITER_CLSID>{171252A0-8820-4AFE-9DF8-5C92B2D66B04}</SPLITER_CLSID>--><!--LAV Splitter-->
	<SPLITER_CLSID></SPLITER_CLSID><!--None : for source filter soing splitter-->
	<DXVA_SPLITER_CLSID></DXVA_SPLITER_CLSID><!--None : for source filter soing splitter-->
	<DEFAULT_DSHOW_DECODER_NAME>{EE30215D-164F-4A92-A4EB-9D4C13390F9F}</DEFAULT_DSHOW_DECODER_NAME>
    <!--DEFAULT_DSHOW_DECODER_NAME>ffdshow Video Decoder</DEFAULT_DSHOW_DECODER_NAME>-->
	<!--<DEFAULT_DSHOW_DECODER_NAME>Microsoft DTV-DVD Video Decoder</DEFAULT_DSHOW_DECODER_NAME>-->
	<!--<DEFAULT_DXVA_DECODER_NAME>Microsoft DTV-DVD Video Decoder</DEFAULT_DXVA_DECODER_NAME>-->
	<DEFAULT_DXVA_DECODER_NAME>{EE30215D-164F-4A92-A4EB-9D4C13390F9F}</DEFAULT_DXVA_DECODER_NAME>
	<!--<DEFAULT_DXVA_DECODER_NAME>Microsoft DTV-DVD Video Decoder</DEFAULT_DXVA_DECODER_NAME>-->
	<!--<DEFAULT_DXVA_DECODER_NAME>ffdshow DXVA Video Decoder</DEFAULT_DXVA_DECODER_NAME>-->
	<DEFAULT_AUDIO_DECODER_CLSID>{E1F1A0B8-BEEE-490D-BA7C-066C40B5E2B9}</DEFAULT_AUDIO_DECODER_CLSID><!--Microsoft DTV-DVD Audio Decoder-->
	<!--<DEFAULT_AUDIO_DECODER_CLSID>{0F40E1E5-4F79-4988-B1A9-CC98794E6B55}</DEFAULT_AUDIO_DECODER_CLSID>--><!--ffdshow Audio Decoder-->
	<!--<AUDIO_RENDERER_CONFIG> 
		<STREAM>
			<LEFT_PERCENT>0</LEFT_PERCENT>
			<TOP_PERCENT>0</TOP_PERCENT>
			<WIDTH_PERCENT>33.33</WIDTH_PERCENT>
			<HEIGHT_PERCENT>100</HEIGHT_PERCENT>
			<RENDERER_NAME>DirectSound: Haut-Parleurs (Sound Blaster X-Fi Xtreme Audio</RENDERER_NAME>
		</STREAM>
		<STREAM>
			<LEFT_PERCENT>33.33</LEFT_PERCENT>
			<TOP_PERCENT>0</TOP_PERCENT>
			<WIDTH_PERCENT>33.33</WIDTH_PERCENT>
			<HEIGHT_PERCENT>100</HEIGHT_PERCENT>
			<RENDERER_NAME>DirectSound: Haut-Parleurs (Generic USB Audio Device</RENDERER_NAME>
		</STREAM>
	</AUDIO_RENDERER_CONFIG>-->
	<VIDEO_CONTROLS_TIMEOUT>30000</VIDEO_CONTROLS_TIMEOUT><!-- interval in ms -->
	<DEFAULT_STREAMS_BACKGROUND_COLOR>#000000</DEFAULT_STREAMS_BACKGROUND_COLOR>
	<DEFAULT_ZONES_BACKGROUND_COLOR>#000000</DEFAULT_ZONES_BACKGROUND_COLOR>
	<DEFAULT_ZONES_BACKGROUND_IMAGE>D:\moodmedia\software_v5\settings\default_black.jpg</DEFAULT_ZONES_BACKGROUND_IMAGE>
	<CAPTURE_DEVICES>D:\moodmedia\software_v5\settings\capture_devices_list.xml</CAPTURE_DEVICES>
	<TUNER_DEVICES>D:\moodmedia\software_v5\settings\tuner_devices_list.xml</TUNER_DEVICES>
	<TV_CHANNELS>D:\moodmedia\software_v5\settings\tv_channels.xml</TV_CHANNELS>
  <AUTO_BRING_TO_FRONT>0</AUTO_BRING_TO_FRONT>
  <FLASHS_WELL_CODED>false</FLASHS_WELL_CODED>
  <DISABLE_BUFFERING>0</DISABLE_BUFFERING><!--default : buffering is enabled)-->
<MINIMIZE_BUFFERING>1</MINIMIZE_BUFFERING><!--default : buffering is minimized to 1x1 Pixel-->
  </ADVANCED>
</VIDEO_ENGINE_SETTINGS>
